"""Initial migration

Revision ID: 046fce19b523
Revises: d65785e9038e
Create Date: 2025-12-08 22:38:35.475365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046fce19b523'
down_revision = 'd65785e9038e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_ip_per_question'), type_='unique')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('unique_ip_per_question'), ['question_id', 'ip_address'])

    # ### end Alembic commands ###
