"""Initial migration

Revision ID: 329b6bf57c60
Revises: 046fce19b523
Create Date: 2025-12-08 22:45:04.523429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329b6bf57c60'
down_revision = '046fce19b523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('choice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index('idx_response_ip', ['ip_address', 'created_at'], unique=False)
        batch_op.create_index('idx_response_session', ['session_id', 'question_id'], unique=False)

    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_code', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('max_responses', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['access_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('max_responses')
        batch_op.drop_column('access_code')

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_index('idx_response_session')
        batch_op.drop_index('idx_response_ip')
        batch_op.alter_column('choice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('session_id')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('text_answer')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('order_index')
        batch_op.drop_column('is_required')

    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###
