"""Initial migration

Revision ID: d65785e9038e
Revises: 9c528addf496
Create Date: 2025-12-08 22:32:11.037839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65785e9038e'
down_revision = '9c528addf496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.alter_column('choice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('unique_ip_per_question', ['question_id', 'ip_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_constraint('unique_ip_per_question', type_='unique')
        batch_op.alter_column('choice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
